### ISSUE TITLE
using tabs to indent

### ISSUE THREAD

**Issue by 842Mono** [amrdraz/python-debugger#1]
cannot indent using tabs. It gives unexpected indent errors

...apparently because when pressing "enter" to go to the next line, the new line is automatically indented using spaces instead of tabs. It doesn't recognise tabs.

**Comment by amrdraz** [comment]
I'm sorry I just pushed an update and tried using tabs, and it worked
could you [try](http://amrdraz.github.io/python-debugger/) again
and elaborate more

give an example of code you ran and didn't work

upload a screenshot to this issue

**Comment by amrdraz** [comment]
This example worked for me
Here I used a mix of tabs and spaces
If block uses single space and else block used one tab

```
x = 10
if x > 10:
 print(x)
 print("Yo")
else:
    print("hey")

```

**Comment by 842Mono** [comment]
that's not what I meant :D

try implementing this code using only tabs to indent

```
i=5
while i!=0:
    print("sth")
    print("sth else")
    i-=1
```

**Comment by 842Mono** [comment]
I mean that when writing the code and I reach this part:

```
i=5
while i!=0:
    print("sth")
    print("sth else")
```

...now I have to "press enter" to write <code>i-=1</code> in the next line. Here the program automatically indents the new line using "four spaces" instead of a tab. Which causes the error.

**Comment by amrdraz** [comment]
Oh, I get it

​Well that's not an error that's a preference, generally python style guide
recommends using 4 spaces instead of tab

accordingly the editor will indeed by default insert 4 spaces by default

I will override the tab key to insert spaces instead of the tab character
that should fix this

**Comment by 842Mono** [comment]
right! that's not really a bug. sorry for that XD thanks :D

**Comment by amrdraz** [comment]
I made it so that tab characters are marked by the editor so that it is visible when a tab is used instead of a space.
I also made it so that the tab key inserts space by default
added in the same commit an arrow when debugging
